name: bda
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - blas=2.116=mkl
  - blas-devel=3.9.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - charset-normalizer=3.1.0
  - cuda-cccl=12.1.109
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - freetype=2.12.1
  - idna=3.4
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lcms2=2.14
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcublas=11.10.3.66
  - libcublas-dev=11.10.3.66
  - libcufft=10.7.2.124
  - libcufft-dev=10.7.2.124
  - libcurand=10.3.2.106
  - libcurand-dev=10.3.2.106
  - libcusolver=11.4.0.1
  - libcusolver-dev=11.4.0.1
  - libcusparse=11.7.4.91
  - libcusparse-dev=11.7.4.91
  - libdeflate=1.14
  - libhwloc=2.9.1
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnpp=11.7.4.75
  - libnpp-dev=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libnvjpeg-dev=11.8.0.2
  - libpng=1.6.39
  - libsqlite=3.42.0
  - libtiff=4.4.0
  - libuv=1.44.2
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxml2=2.11.4
  - libzlib=1.2.13
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - msys2-conda-epoch=20160418
  - numpy=1.21.6
  - openjpeg=2.5.0
  - openssl=3.1.1
  - pillow=9.2.0
  - pip=23.1.2
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pysocks=1.7.1
  - python=3.7.12
  - python_abi=3.7
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - requests=2.31.0
  - setuptools=67.7.2
  - sqlite=3.42.0
  - tbb=2021.9.0
  - tk=8.6.12
  - typing_extensions=4.6.2
  - ucrt=10.0.22621.0
  - urllib3=2.0.2
  - vc=14.3
  - vc14_runtime=14.34.31931
  - vs2015_runtime=14.34.31931
  - wheel=0.40.0
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zstd=1.5.2
  - pip:
      - colorama==0.4.6
      - cycler==0.11.0
      - efficientnet-pytorch==0.7.1
      - filelock==3.12.0
      - fonttools==4.38.0
      - fsspec==2023.1.0
      - huggingface-hub==0.15.1
      - importlib-metadata==6.6.0
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - matplotlib==3.5.3
      - munch==3.0.0
      - packaging==23.1
      - pandas==1.3.5
      - pretrainedmodels==0.7.4
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyyaml==6.0
      - safetensors==0.3.1
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - segmentation-models-pytorch==0.3.3
      - six==1.16.0
      - threadpoolctl==3.1.0
      - tifffile==2021.11.2
      - timm==0.9.2
      - torchaudio==0.13.1
      - torchvision==0.14.1
      - tqdm==4.65.0
      - zipp==3.15